application: ams-django-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: myproject.wsgi.application

module: default

libraries:
- name: django
  version: 1.5
